In [7]:
import numpy as np
from numpy import array, matmul, dot, zeros, ones, eye, diag, polyfit, transpose
from numpy.linalg import solve, norm, det, eig, eigh, eigvals, eigvalsh, inv, lstsq, svd, matrix_power, matrix_rank
from numpy.random import randn, rand, randint, seed
from math import pi, sin, cos
import pandas as pd

In [92]:
data = np.array([['','ADO', 'AJA', 'AZ', 'EXC', 'FEY', 'GRO', 'HEE', 'HER', 'NAC', 'PEC', 'PSV', 'RJC', 'SPA', 'TWE', 'UTR', 'VIT', 'VVV', 'WIL'], 
              ['ADO',0., 1., 0., 0., 1., 0., 0., 3., 0., 3., 1., 3., 3., 3., 0., 3., 1., 3.],
              ['AJA',1,0,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3],
              ['AZ',3,0,0,0,0,3,3,3,3,3,0,1,3,3,3,3,1,3],
              ['EXC',0,0,0,0,0,3,0,1,1,0,0,3,1,1,1,0,0,3],
              ['FEY',3,0,3,3,0,3,1,3,0,1,0,3,3,3,3,3,1,3],
              ['GRO',1,0,1,3,0,0,1,1,1,3,1,3,3,3,3,3,1,0],
              ['HEE',3,0,0,0,0,1,0,1,3,0,3,1,3,3,1,0,1,3],
              ['HER',1,3,0,1,0,3,0,0,3,3,0,3,3,3,1,1,3,3],
              ['NAC',0,0,0,3,3,3,3,3,0,0,0,0,1,0,3,3,0,0],
              ['PEC',3,0,1,1,0,3,3,3,3,0,0,3,3,3,1,0,1,0],
              ['PSV',3,3,3,3,3,1,1,3,3,3,0,0,3,3,3,3,3,3],
              ['RJC',0,0,0,3,1,1,3,0,3,3,1,0,0,1,0,0,0,0],
              ['SPA',3,0,0,0,0,3,1,0,0,3,1,0,0,3,0,0,3,3],
              ['TWE',0,1,0,0,0,1,0,3,1,3,0,3,1,0,3,1,0,1],
              ['UTR',1,1,1,3,1,1,3,1,1,3,0,3,3,3,0,3,3,3],
              ['VIT',3,3,0,0,3,3,1,1,3,1,0,0,3,3,1,0,1,1],
              ['VVV',0,0,0,0,3,1,0,3,1,1,0,0,3,1,0,1,0,1],
              ['WIL',0,0,0,0,0,1,0,3,1,0,3,3,1,3,3,1,3,0],
             ])

pd.DataFrame(data=data[1:,1:],    # values
             index=data[1:,0],    # 1st column as index
             columns=data[0,1:])  # 1st row as the column names

ADO  AJA   AZ  EXC  FEY  GRO  HEE  HER  NAC  PEC  PSV  RJC  SPA  TWE  \
ADO  0.0  1.0  0.0  0.0  1.0  0.0  0.0  3.0  0.0  3.0  1.0  3.0  3.0  3.0   
AJA    1    0    3    3    3    3    3    3    3    3    3    3    3    3   
AZ     3    0    0    0    0    3    3    3    3    3    0    1    3    3   
EXC    0    0    0    0    0    3    0    1    1    0    0    3    1    1   
FEY    3    0    3    3    0    3    1    3    0    1    0    3    3    3   
GRO    1    0    1    3    0    0    1    1    1    3    1    3    3    3   
HEE    3    0    0    0    0    1    0    1    3    0    3    1    3    3   
HER    1    3    0    1    0    3    0    0    3    3    0    3    3    3   
NAC    0    0    0    3    3    3    3    3    0    0    0    0    1    0   
PEC    3    0    1    1    0    3    3    3    3    0    0    3    3    3   
PSV    3    3    3    3    3    1    1    3    3    3    0    0    3    3   
RJC    0    0    0    3    1    1    3    0    3    3    1    0    0    1   
SPA    3    0    0    0    0    3    1    0    0    3    1    0    0    3   
TWE    0    1    0    0    0    1    0    3    1    3    0    3    1    0   
UTR    1    1    1    3    1    1    3    1    1    3    0    3    3    3   
VIT    3    3    0    0    3    3    1    1    3    1    0    0    3    3   
VVV    0    0    0    0    3    1    0    3    1    1    0    0    3    1   
WIL    0    0    0    0    0    1    0    3    1    0    3    3    1    3   

     UTR  VIT  VVV  WIL  
ADO  0.0  3.0  1.0  3.0  
AJA    0    0    3    3  
AZ     3    3    1    3  
EXC    1    0    0    3  
FEY    3    3    1    3  
GRO    3    3    1    0  
HEE    1    0    1    3  
HER    1    1    3    3  
NAC    3    3    0    0  
PEC    1    0    1    0  
PSV    3    3    3    3  
RJC    0    0    0    0  
SPA    0    0    3    3  
TWE    3    1    0    1  
UTR    0    3    3    3  
VIT    1    0    1    1  
VVV    0    1    0    1  
WIL    3    1    3    0

# Define G
This needs to be filled in manually

In [90]:
G = np.array([[0., 1., 0., 0., 1., 0., 0., 3., 0., 3., 1., 3., 3., 3., 0., 3., 1., 3.],
              [1., 0., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 0., 0., 3., 3.],
              [3., 0., 0., 0., 0., 3., 3., 3., 3., 3., 0., 1., 3., 3., 3., 3., 1., 3.],
              [0., 0., 0., 0., 0., 3., 0., 1., 1., 0., 0., 3., 1., 1., 1., 0., 0., 3.],
              [3., 0., 3., 3., 0., 3., 1., 3., 0., 1., 0., 3., 3., 3., 3., 3., 1., 3.],
              [1., 0., 1., 3., 0., 0., 1., 1., 1., 3., 1., 3., 3., 3., 3., 3., 1., 0.],
              [3., 0., 0., 0., 0., 1., 0., 1., 3., 0., 3., 1., 3., 3., 1., 0., 1., 3.],
              [1., 3., 0., 1., 0., 3., 0., 0., 3., 3., 0., 3., 3., 3., 1., 1., 3., 3.],
              [0., 0., 0., 3., 3., 3., 3., 3., 0., 0., 0., 0., 1., 0., 3., 3., 0., 0.],
              [3., 0., 1., 1., 0., 3., 3., 3., 3., 0., 0., 3., 3., 3., 1., 0., 1., 0.],
              [3., 3., 3., 3., 3., 1., 1., 3., 3., 3., 0., 0., 3., 3., 3., 3., 3., 3.],
              [0., 0., 0., 3., 1., 1., 3., 0., 3., 3., 1., 0., 0., 1., 0., 0., 0., 0.],
              [3., 0., 0., 0., 0., 3., 1., 0., 0., 3., 1., 0., 0., 3., 0., 0., 3., 3.],
              [0., 1., 0., 0., 0., 1., 0., 3., 1., 3., 0., 3., 1., 0., 3., 1., 0., 1.],
              [1., 1., 1., 3., 1., 1., 3., 1., 1., 3., 0., 3., 3., 3., 0., 3., 3., 3.],
              [3., 3., 0., 0., 3., 3., 1., 1., 3., 1., 0., 0., 3., 3., 1., 0., 1., 1.],
              [0., 0., 0., 0., 3., 1., 0., 3., 1., 1., 0., 0., 3., 1., 0., 1., 0., 1.],
              [0., 0., 0., 0., 0., 1., 0., 3., 1., 0., 3., 3., 1., 3., 3., 1., 3., 0.]])

# Define $\hat{G}$
This is a column stochastic matrix. Just run code that uses the G-matrix.

In [91]:
G_hat = G.copy()
for col in range(len(G)):
    for row in range(len(G)):
        print(row, col)
        G_hat[row,col] = G[row,col]/sum(G[:,col])

0 0
1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
9 0
10 0
11 0
12 0
13 0
14 0
15 0
16 0
17 0
0 1
1 1
2 1
3 1
4 1
5 1
6 1
7 1
8 1
9 1
10 1
11 1
12 1
13 1
14 1
15 1
16 1
17 1
0 2
1 2
2 2
3 2
4 2
5 2
6 2
7 2
8 2
9 2
10 2
11 2
12 2
13 2
14 2
15 2
16 2
17 2
0 3
1 3
2 3
3 3
4 3
5 3
6 3
7 3
8 3
9 3
10 3
11 3
12 3
13 3
14 3
15 3
16 3
17 3
0 4
1 4
2 4
3 4
4 4
5 4
6 4
7 4
8 4
9 4
10 4
11 4
12 4
13 4
14 4
15 4
16 4
17 4
0 5
1 5
2 5
3 5
4 5
5 5
6 5
7 5
8 5
9 5
10 5
11 5
12 5
13 5
14 5
15 5
16 5
17 5
0 6
1 6
2 6
3 6
4 6
5 6
6 6
7 6
8 6
9 6
10 6
11 6
12 6
13 6
14 6
15 6
16 6
17 6
0 7
1 7
2 7
3 7
4 7
5 7
6 7
7 7
8 7
9 7
10 7
11 7
12 7
13 7
14 7
15 7
16 7
17 7
0 8
1 8
2 8
3 8
4 8
5 8
6 8
7 8
8 8
9 8
10 8
11 8
12 8
13 8
14 8
15 8
16 8
17 8
0 9
1 9
2 9
3 9
4 9
5 9
6 9
7 9
8 9
9 9
10 9
11 9
12 9
13 9
14 9
15 9
16 9
17 9
0 10
1 10
2 10
3 10
4 10
5 10
6 10
7 10
8 10
9 10
10 10
11 10
12 10
13 10
14 10
15 10
16 10
17 10
0 11
1 11
2 11
3 11
4 11
5 11
6 11
7 11
8 11
9 11
10 11
11 11
12 11
13 11
14 11
15 11
16 11
17 11
0 12

In [75]:
G_hat

array([[0.        , 0.08333333, 0.        , 0.        , 0.05555556,
        0.        , 0.        , 0.08571429, 0.        , 0.09090909,
        0.07692308, 0.09375   , 0.075     , 0.07142857, 0.        ,
        0.12      , 0.04      , 0.09090909],
       [0.04      , 0.        , 0.25      , 0.13043478, 0.16666667,
        0.08823529, 0.13043478, 0.08571429, 0.1       , 0.09090909,
        0.23076923, 0.09375   , 0.075     , 0.07142857, 0.        ,
        0.        , 0.12      , 0.09090909],
       [0.12      , 0.        , 0.        , 0.        , 0.        ,
        0.08823529, 0.13043478, 0.08571429, 0.1       , 0.09090909,
        0.        , 0.03125   , 0.075     , 0.07142857, 0.11538462,
        0.12      , 0.04      , 0.09090909],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.08823529, 0.        , 0.02857143, 0.03333333, 0.        ,
        0.        , 0.09375   , 0.025     , 0.02380952, 0.03846154,
        0.        , 0.        , 0.09090909],
    

# Now define the Google PageRank A-matrix (Random walk)
The percentage can be changed such that it uses random walk.

In [86]:
p = 0.85
n = 18
A = p * G_hat + (1-p) * ones([n,n]) * 1/n
print(A)

# Check if it is a column-stochastic matrix
print('\nCheck if column-stochastic')
for col in range(len(A)):
    print(sum(A[:,col]))

[[0.00833333 0.07916667 0.00833333 0.00833333 0.05555556 0.00833333
  0.00833333 0.08119048 0.00833333 0.08560606 0.07371795 0.08802083
  0.07208333 0.06904762 0.00833333 0.11033333 0.04233333 0.08560606]
 [0.04233333 0.00833333 0.22083333 0.1192029  0.15       0.08333333
  0.1192029  0.08119048 0.09333333 0.08560606 0.20448718 0.08802083
  0.07208333 0.06904762 0.00833333 0.00833333 0.11033333 0.08560606]
 [0.11033333 0.00833333 0.00833333 0.00833333 0.00833333 0.08333333
  0.1192029  0.08119048 0.09333333 0.08560606 0.00833333 0.03489583
  0.07208333 0.06904762 0.10641026 0.11033333 0.04233333 0.08560606]
 [0.00833333 0.00833333 0.00833333 0.00833333 0.00833333 0.08333333
  0.00833333 0.03261905 0.03666667 0.00833333 0.00833333 0.08802083
  0.02958333 0.02857143 0.04102564 0.00833333 0.00833333 0.08560606]
 [0.11033333 0.00833333 0.22083333 0.1192029  0.00833333 0.08333333
  0.04528986 0.08119048 0.00833333 0.03409091 0.00833333 0.08802083
  0.07208333 0.06904762 0.10641026 0.1103333

In [97]:
eigenvalues, eigenvectors = eig(A)
eigenvalues

array([ 1.        +0.j        , -0.05351183+0.21813846j,
       -0.05351183-0.21813846j, -0.20723314+0.j        ,
       -0.13811333+0.13442167j, -0.13811333-0.13442167j,
       -0.02192647+0.11457015j, -0.02192647-0.11457015j,
       -0.12059181+0.04815068j, -0.12059181-0.04815068j,
       -0.1129914 +0.j        ,  0.06100882+0.03405942j,
        0.06100882-0.03405942j,  0.02608081+0.05283892j,
        0.02608081-0.05283892j,  0.04022914+0.j        ,
       -0.03794849+0.0247554j , -0.03794849-0.0247554j ])

In [98]:
for val in range(len(eigenvalues)):
    if eigenvalues[val] == 1.:
        print('yeah')

# Eigenvector for eigenvalue 1

In [99]:
eigenvectors[0]

array([-0.21276789+0.j        ,  0.22099884-0.08130897j,
        0.22099884+0.08130897j, -0.40309214+0.j        ,
       -0.04280613+0.04559472j, -0.04280613-0.04559472j,
        0.08814493-0.28903649j,  0.08814493+0.28903649j,
       -0.10501231-0.09862984j, -0.10501231+0.09862984j,
       -0.11553974+0.j        , -0.08701831+0.00708177j,
       -0.08701831-0.00708177j,  0.03010526+0.03561076j,
        0.03010526-0.03561076j,  0.19280963+0.j        ,
       -0.23304619-0.14829908j, -0.23304619+0.14829908j])